OpenMM: ThreeParticleAverageSite Class Reference
ThreeParticleAverageSite Class Reference
This is a VirtualSite that computes the particle location as a weighted average of three other particle's locations.
Public Member Functions
def getWeight
getWeight(ThreeParticleAverageSite self, int particle) -> double
def __init__
init(OpenMM::ThreeParticleAverageSite self, int particle1, int particle2, int particle3, double weight1, double weight2, double weight3) -> ThreeParticleAverageSite init(OpenMM::ThreeParticleAverageSite self, ThreeParticleAverageSite other) -> ThreeParticleAverageSite
def __del__
del(OpenMM::ThreeParticleAverageSite self)
Public Member Functions inherited from VirtualSite
def __init__
def __del__
del(OpenMM::VirtualSite self)
def getNumParticles
getNumParticles(VirtualSite self) -> int
def getParticle
getParticle(VirtualSite self, int particle) -> int
Public Attributes
this
Detailed Description
This is a VirtualSite that computes the particle location as a weighted average of three other particle's locations.
Assuming the weights add up to 1, this means the virtual site is in the plane of the three particles.
Constructor & Destructor Documentation
def __init__ (self, args)
init(OpenMM::ThreeParticleAverageSite self, int particle1, int particle2, int particle3, double weight1, double weight2, double weight3) -> ThreeParticleAverageSite init(OpenMM::ThreeParticleAverageSite self, ThreeParticleAverageSite other) -> ThreeParticleAverageSite
Create a new ThreeParticleAverageSite virtual site. Normally the weights should add up to 1, although this is not strictly required.
Parameters
particle1 the index of the first particle
particle2 the index of the second particle
particle3 the index of the third particle
weight1 the weight factor (between 0 and 1) for the first particle
weight2 the weight factor (between 0 and 1) for the second particle
weight2 the weight factor (between 0 and 1) for the third particle
References simtk.openmm.openmm.stripUnits().
def __del__ (self)
del(OpenMM::ThreeParticleAverageSite self)
References simtk.openmm.openmm.stripUnits().
Member Function Documentation
def getWeight (self, args)
getWeight(ThreeParticleAverageSite self, int particle) -> double
Get the weight factor used for a particle this virtual site depends on.
Parameters
particle the particle to get (between 0 and getNumParticles())
References simtk.openmm.openmm.stripUnits().
Member Data Documentation
this
Referenced by System.__init__().
The documentation for this class was generated from the following file:
openmm.py